# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  inventory:
    image: inventory
    build:
      context: .
      dockerfile: ./Inventory.WebApi/Dockerfile
    ports:
      - 5001
    environment:
      - ASPNETCORE_URLS=http://+:5001
